name: Build and Release Debian Package

on:
  push:
    tags:
      - "*"

jobs:
  build_and_release:
    name: Build and Release Debian Package
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install DKMS
        run: sudo apt-get install -y debhelper devscripts dh-exec dkms dpkg

      - name: Build Debian package
        run: dkms mkdeb --source-only

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            ../*.deb

  build_apt_repository:
    name: Build Private APT repository GitHub Pages
    runs-on: ubuntu-24.04
    needs: build_and_release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: import gpg key
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build APT repository
        run: |
          ./make_apt_pages.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build_apt_repository
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy pages
        uses: actions/deploy-pages@v4
